import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import 'normalize.css/normalize.css';
import NavBar from "./ui/navbar";
import { Banner } from "./ui/banner";
import { SideNav } from "./sideNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): JSX.Element {
  return (
    <html lang="en">
      <body className={inter.className}>

        <NavBar />

        <Banner />

        <div className="container">
          
          <SideNav />

          <main>
            {children}
          </main>

        </div>

      </body>
    </html>
  );
}
